[tool.poetry]
name = "manim-smart-algebra"
version = "0.3.0"
description = "Manim plugin which simplifies the process of animating algebra"
authors = ["John Connell <johnconnelltutor@gmail.com>"]
license = "MIT"
repository = "https://github.com/TheMathematicFanatic/manim_smart_algebra"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<=3.12"
manim = ">=0.17"

[tool.poetry.plugins."manim.plugins"]
"manim_play_timeline" = "manim_play_timeline"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"